services:
  - type: web
    name: automator-backend
    runtime: node
    buildCommand: yarn install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
